# =========================================================
# MEDIATEK (MTK) - ASIA REGION
# =========================================================
NTP_SERVER=asia.pool.ntp.org
NTP_SERVER_2=0.asia.pool.ntp.org
NTP_SERVER_3=time.google.com

SUPL_HOST=supl.google.com
SUPL_PORT=7276
SUPL_VER=0x20001
SUPL_MODE=1
SUPL_ES=0

CAPABILITIES=0x37
ACCURACY_THRES=0
INTERMEDIATE_POS=0

# MediaTek EPO / AGPS Settings
AGPS_CONFIG_INJECT=1
ENABLE_EPO=1
EPO_URL=http://epo.mediatek.com

NFW_CLIENT_CP=com.google.android.gms
NFW_CLIENT_SUPL=com.google.android.gms

DEBUG_LEVEL=0
QXDM_LOG=0
LOG_BUFFER_ENABLED=0
